# Generated by Django 3.2.5 on 2021-08-12 00:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Child_First_Name', models.CharField(max_length=100)),
                ('Child_Last_Name', models.CharField(max_length=100)),
                ('Any_Allergies', multiselectfield.db.fields.MultiSelectField(choices=[('milk', 'milk'), ('eggs', 'eggs'), ('soybean', 'soybean'), ('fish', 'fish'), ('shellfish', 'shellfish'), ('treenuts', 'treenuts'), ('peanuts', 'peanuts'), ('wheat', 'wheat')], max_length=55)),
            ],
        ),
    ]
