# Generated by Django 3.2.5 on 2021-08-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyOrganicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerForm',
            new_name='CustomerModelForm',
        ),
    ]
