# Generated by Django 3.2.5 on 2021-08-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyOrganicApp', '0002_rename_customerform_customermodelform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModelForm',
            new_name='CustomerFormModel',
        ),
    ]
