# Generated by Django 3.2.5 on 2021-08-09 03:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tinyOrganicApp', '0003_rename_customermodelform_customerformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerformmodel',
            name='anyAlergies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('milk', 'eggs'), ('soybean', 'fish'), ('shellfish', 'treenuts'), ('peanuts', 'wheat')], max_length=30),
        ),
    ]
